Helpful error messages when cell temperature heat transfer method is missing data
NREL/ssc pull request #1086
Opened 2023-11-03 19:42 UTC by mjprilliman

-Throw error in pvsamv1 when ambient pressure and dew point (or wet bulb) is missing from the weather file
-Make tcell nan when this happens to make sure calculation does not continue as normal
-Fixes https://github.com/NREL/sam/issues/1428

2023-11-03 19:43 UTC, mjprilliman commented
@cpaulgilman review for error message.
@sjanzou review on if there is a better way of handling this error?

2023-11-03 20:48 UTC, cpaulgilman approved these changes
Looks good. Here are weather files I used for testing with heat transfer cell temp model: 
[weather-files-for-heat-transfer-cell-temp-tests.zip](https://github.com/NREL/ssc/files/13254565/weather-files-for-heat-transfer-cell-temp-tests.zip)

2023-11-05 07:45 UTC, sjanzou requested changes
Please change isnan to std::isnan throughout changes per https://github.com/NREL/SAM/issues/1223

2023-11-05 07:45 UTC, sjanzou commented on shared/lib_cec6par.cpp
> +    if (isnan(input.Patm)) {
Please use std::isnan instead of isnan, see https://github.com/NREL/SAM/issues/1223

2023-11-05 07:45 UTC, sjanzou commented on shared/lib_cec6par.cpp
> +    if (isnan(input.Tdew)) {
std::isnan()

2023-11-05 07:45 UTC, sjanzou commented on ssc/cmod_pvsamv1.cpp
> +                            if (isnan(tcell)) throw exec_error("pvsamv1", Subarrays[nn]->Module->cellTempModel->error());
std::isnan please...

2023-11-07 05:29 UTC, sjanzou approved these changes
Thanks for updating!

2023-11-07 17:28 UTC, merged