Update for pysam hybrids
NREL/ssc pull request #1091
Opened 2023-11-16 18:26 UTC by dguittet

The input technologies to `cmod_hybrid` require some financial variables that aren't listed as required, and aren't checked by the cmod. In PySAM, this means if the user doesn't have these extra financial variables, the cmod will just have a hard exit. Fix this by making a `vtab_hybrid_tech_om_inputs` that isn't added to any of the compute modules, but is added dynamically by `cmod_hybrid` to check that all these variables are present.

Other changes to `cmod_hybrid`:
 - Move check of required input input_tables to beginning of `exec`
 - Use `inflation_rate` and `analysis_period` from the "Hybrid" input_table which includes the financial cmods. The code originally requires each cmod to have its own `inflation_rate` and `analysis_period` which is problematic because not all technology cmods have these as inputs, and it seems to make it possible to have different values. However, this requires there to be a financial cmod to the hybrid cmod, and this is currently not enforced. Should a financial model be required for running a hybrid cmod?
 - Not all technology cmods have `system_use_lifetime_output`, such as `windpower`, so instead of adding a new interface variable to these cmods, I made cmod_hybrid assume False unless the variable is available and True.

Happy to discuss concerns about any of these proposed changes.

2023-11-26 11:37 UTC, sjanzou commented
> The input technologies to `cmod_hybrid` require some financial variables that aren't listed as required, and aren't checked by the cmod. In PySAM, this means if the user doesn't have these extra financial variables, the cmod will just have a hard exit. Fix this by making a `vtab_hybrid_tech_om_inputs` that isn't added to any of the compute modules, but is added dynamically by `cmod_hybrid` to check that all these variables are present.
> 
> Other changes to `cmod_hybrid`:
> 
> * Move check of required input input_tables to beginning of `exec`
> * Use `inflation_rate` and `analysis_period` from the "Hybrid" input_table which includes the financial cmods. The code originally requires each cmod to have its own `inflation_rate` and `analysis_period` which is problematic because not all technology cmods have these as inputs, and it seems to make it possible to have different values. However, this requires there to be a financial cmod to the hybrid cmod, and this is currently not enforced. Should a financial model be required for running a hybrid cmod?
> * Not all technology cmods have `system_use_lifetime_output`, such as `windpower`, so instead of adding a new interface variable to these cmods, I made cmod_hybrid assume False unless the variable is available and True.
> 
> Happy to discuss concerns about any of these proposed changes.

A financial compute module is currently required to run a hybrid compute module. We can revisit in the future. Required for the o and m and installation costs for each hybrid component separately in a hybrid system. The technology compute modules do not require the costs to run.

The battery and fuel cell compute modules are run in lifetime mode regardless of the generator compute modules lifetime mode settings.

2024-02-16 06:58 UTC, sjanzou commented
@dguittet, are you working on this branch or a different one for patch 1? Thanks!

2024-02-16 18:43 UTC, dguittet commented
@sjanzou Yes, this is the one still.

2024-02-19 12:29 UTC, sjanzou requested changes
One test failing on Windows - all others are passing!
[  FAILED  ] CmodHybridTest.GenericPVWattsWindFuelCellBatteryHybrid_SingleOwner

2024-02-22 07:42 UTC, sjanzou commented on ssc/cmod_hybrid.cpp
> +                        degrad = input.as_array("degradation", &count_degrad);
generic_degradation is input to both cmod_generic_system and cmod_mhk_wave and is in the UI in Degradation AC Lifetime form as follows:
![image](https://github.com/NREL/ssc/assets/6498311/ffacb3b4-0bc2-44a3-9f3a-09f678dcbe7c)

So, is used throughout the generic system.

Also, "degradation" is only used for non-lifetime simulation like PVWatts, pvsamv1 applies degradation outside of cmod_hybrid and is not used in cmod_hybrid (true for all generators with system_use_lifetime_output non-zero):
![image](https://github.com/NREL/ssc/assets/6498311/439e3d91-c2b9-47ed-a97b-15958b9b9003)

The code you showed for cmod_hybrid appears to be out of date... generic_degradation is not used in cmod_hybrid - when did you last merge patch into pysam_hybrids? Did it merge the latest from patch?

The latest patch branch does not have the lines 217 through 220 that you showed
https://github.com/NREL/ssc/blob/patch/ssc/cmod_hybrid.cpp

2024-02-27 23:11 UTC, dguittet commented on ssc/sscapi.cpp
> +
add comment for why 35

2024-02-27 23:12 UTC, dguittet commented on ssc/cmod_fuelcell.cpp
> +    add_var_info(vtab_hybrid_tech_om_outputs);
move into hybridize?

2024-02-27 23:14 UTC, dguittet commented on ssc/cmod_hybrid.cpp
> +            ssc_number_t sales_tax_rate = financial_compute_modules->table.lookup("sales_tax_rate")->num * 0.01;
Comment out and check tests

2024-02-27 23:15 UTC, dguittet commented on ssc/cmod_hybrid.cpp
> +                        input.assign("generic_degradation", *input.lookup("degradation"));
@sjanzou Can check this?

2024-02-27 23:17 UTC, dguittet commented on ssc/cmod_hybrid.cpp
> +                if (compute_module_inputs->table.lookup("system_heat_rate")) {
trying to prevent seg fault of accessing the following variables

2024-02-27 23:18 UTC, dguittet commented on ssc/cmod_hybrid.cpp
> +                compute_module_inputs->table.assign("ppa_price_input", *financial_compute_modules->table.lookup("ppa_price_input"));
reformat, and hopefully this makes sense and aligns with UI logic

2024-03-04 18:21 UTC, dguittet commented
@sjanzou Ready for review now that tests are updated from code generator and passing

2024-03-06 11:49 UTC, sjanzou approved these changes
Working on windows and results matching with patch branches ssc and SAM.

Great work!

2024-03-06 11:50 UTC, merged