Remove fuelcell and battery outputs from cases without those systems
NREL/ssc pull request #570
Opened 2021-04-29 19:42 UTC by mjprilliman

-Added assignment checks to only output fuel cell and battery OandM and replacement cost outputs when there is a fuelcell or battery, respectively
-Removed battery efficiency, AC loss, and DC loss for cases without a battery
-Closes https://github.com/NREL/SAM/issues/510
-Closes https://github.com/NREL/SAM/issues/448

2021-04-29 22:38 UTC, brtietz requested changes
Thanks for cleaning all of this up! I had one request on the replacement options, since I consider it easier to handle zeroes than nans when comparing the "no replacements" cases to other cases. Other than that looks good!

2021-04-29 22:38 UTC, brtietz commented on ssc/cmod_merchantplant.cpp
> +        if ((as_integer("en_batt") == 1) && (as_integer("batt_replacement_option") > 0)) {
Mind removing the second half of this if statement ("batt_replacement_option")? Some of the work I'm doing right now compares cases using "no replacement" to various replacement strategies, so having zeroes come out of SSC is useful to that workflow.

2021-04-29 22:38 UTC, brtietz commented on ssc/cmod_singleowner.cpp
> +        if (is_assigned("fuelcell_replacement_option") && (as_integer("fuelcell_replacement_option") > 0)) {
Might want to apply the same logic to fuel cell replacement option as batteries above.

2021-04-30 16:22 UTC, cpaulgilman requested changes
Changes look good to me, and agree with Brian's suggestions.

Since this touches cmod_singleowner,cpp, could you fix the group name for issuance_of_equity in the inputs var table? It looks like someone accidentally pasted into it. It should be "Cash Flow Total and Returns" instead of "TCash Flow Total and Returnsotal Cash Flow and Return":

https://github.com/NREL/ssc/blob/158dcee9bc291dfb043c3fbfa6e90d5960703870/ssc/cmod_singleowner.cpp#L628

2021-04-30 19:33 UTC, brtietz approved these changes

2021-04-30 21:32 UTC, merged