Fix broken CentOS7 build
NREL/ssc pull request #649
Opened 2021-11-10 09:50 UTC by sjanzou

2021-11-10 15:54 UTC, tyneises requested changes
I committed a slightly different version to your branch. If you don't like that, I'm fine using your fix.

2021-11-11 12:07 UTC, sjanzou commented
11/11/2021 2am build and run on CentOS7 
![image](https://user-images.githubusercontent.com/6498311/141295346-431ff5cc-4a59-4ff4-b201-6fa33ad3c405.png)

2021-11-11 15:20 UTC, tyneises approved these changes

2021-11-11 20:52 UTC, brtietz approved these changes

2021-11-12 03:18 UTC, merged