LCOE calculations with parasitic load costs in numerator, Energy sales in denominator
NREL/ssc pull request #651
Opened 2021-11-10 22:46 UTC by mjprilliman

-Updated LCOE calculation in all financial models
-Parasitic load operating cost based on PPA price or retail rate for FOM
-Parasitic load operating cost based on hourly prices for BTM
-Variable generation O&M calculated based on energy of value (FOM-sales, BTM-to grid or to load) not net energy
-LCOS updated with same LCOE methods for calculation of cost of grid charging
-Closes #546 outside of larger powerflow changes

2021-11-11 16:39 UTC, cpaulgilman commented
@mjprilliman What branch of SAM is best to test this with?

2021-11-11 16:40 UTC, mjprilliman commented
> @mjprilliman What branch of SAM is best to test this with?

Identical branch name in SAM. https://github.com/NREL/SAM/pull/749

2021-11-15 00:09 UTC, cpaulgilman reviewed
I'm not sure how to evaluate these changes to the LCOE, but it seems to be working as intended.

I added electricity purchases to cash flow for Detailed PV / PPA configs. Not sure if it should also be added for other technologies.

SAM crashes for CSP systems: 

1. Create CSP / Single Owner case.
2. Go to Electricity Purchases page
3. Choose **Retail electricity rate(s) option**

2021-11-15 01:29 UTC, mjprilliman commented
> I'm not sure how to evaluate these changes to the LCOE, but it seems to be working as intended.
> 
> I added electricity purchases to cash flow for Detailed PV / PPA configs. Not sure if it should also be added for other technologies.
> 
> SAM crashes for CSP systems:
> 
> 1. Create CSP / Single Owner case.
> 2. Go to Electricity Purchases page
> 3. Choose **Retail electricity rate(s) option**

Either through code merges or a mistake on my part en_electricity_rates was calculated in the equations and updated in the callbacks, which was causing intermittent crashing for every configuration. Hoping the most recent push will fix the crashing, running the test script now.

2021-11-15 18:10 UTC, cpaulgilman commented
If we are making the electricity purchases option (use PPA or market prices / use retail electricity rates) available for all FOM configurations in the UI, then the FOM financial models need to be updated to calculate cf_energy_purchases_value and cf_utility_bill and include it in the revenue and operating expenses calculation as appropriate. 

As of now, this is handled for single owner, but not all equity partnership flip, leveraged partnership flip, sale leaseback, or merchant plant.

I have a modification to cashflow.lk that adds cf_energy_purchases_value and cf_utility_bill to the cash flow in the UI that I can commit to this branch if we are taking that path. This change would also require updating all of the send-to-Excel with equations workbooks.

2021-11-15 22:54 UTC, brtietz requested changes
My code review found a few typos worth fixing.

It also looks like lnte in Third Party uses CF_energy_net in the denominator - should this be updated as well?

2021-11-15 22:54 UTC, brtietz commented on ssc/cmod_equpartflip.cpp
> +            throw exec_error("singleowner", "PPA price from which to calculate parasitic load costs is not specified. Check inputs for Revenue and Electricity Purchases.");
Please change the cmod name in the error message

2021-11-15 22:54 UTC, brtietz commented on ssc/cmod_cashloan.cpp
> +		double npv_energy_nom = npv( CF_energy_sales, nyears, nom_discount_rate ) + npv(CF_parasitic_cost, nyears, nom_discount_rate);
I thought CF_parasitic_cost went in the numerator. This is the energy term in the denominator of the nominal LCOE.

2021-11-15 22:54 UTC, brtietz commented on ssc/cmod_host_developer.cpp
>  	double host_lcoe_nom = -(cf.at(CF_after_tax_net_equity_cost_flow, 0) + npv(CF_after_tax_net_equity_cost_flow, nyears, host_nom_discount_rate)) * 100;
I see where the parasitics are included in the real LCOE, but what about nominal?

2021-11-15 23:57 UTC, mjprilliman commented
> If we are making the electricity purchases option (use PPA or market prices / use retail electricity rates) available for all FOM configurations in the UI, then the FOM financial models need to be updated to calculate cf_energy_purchases_value and cf_utility_bill and include it in the revenue and operating expenses calculation as appropriate.
> 
> As of now, this is handled for single owner, but not all equity partnership flip, leveraged partnership flip, sale leaseback, or merchant plant.
> 
> I have a modification to cashflow.lk that adds cf_energy_purchases_value and cf_utility_bill to the cash flow in the UI that I can commit to this branch if we are taking that path. This change would also require updating all of the send-to-Excel with equations workbooks.

I'm cleaning up the cash flow outputs in the other FOM financial models (as well as fixing the issues Brian found). So it would now be possible to have the energy purchases and utility bill in the cash flow and Send to Excel for each. I'm not opposed to eliminating the option for some FOM configurations, but how do we decide which configs have that option and which do not?

2021-11-16 00:06 UTC, cpaulgilman commented
> > If we are making the electricity purchases option (use PPA or market prices / use retail electricity rates) available for all FOM configurations in the UI, then the FOM financial models need to be updated to calculate cf_energy_purchases_value and cf_utility_bill and include it in the revenue and operating expenses calculation as appropriate.
> > As of now, this is handled for single owner, but not all equity partnership flip, leveraged partnership flip, sale leaseback, or merchant plant.
> > I have a modification to cashflow.lk that adds cf_energy_purchases_value and cf_utility_bill to the cash flow in the UI that I can commit to this branch if we are taking that path. This change would also require updating all of the send-to-Excel with equations workbooks.
> 
> I'm cleaning up the cash flow outputs in the other FOM financial models (as well as fixing the issues Brian found). So it would now be possible to have the energy purchases and utility bill in the cash flow and Send to Excel for each. I'm not opposed to eliminating the option for some FOM configurations, but how do we decide which configs have that option and which do not?

I think we should make the option available for all FOM configurations. I'll commit my cashflow.lk that includes those outputs in the cash flow for all FOM configs so you can test with your changes to the financial models.

2021-11-16 18:36 UTC, brtietz reviewed
This is close. I think taking two steps for cleanliness would help a lot:

(1) Do a search for <//cf> and see if the line is supposed to be commented out. If yes, delete it and associated comments.

(2) Do a search for <throw exec_error("singleowner"> in compute modules that are not singleowner and update the cmod name appropriately.

The brackets in the above are just to indicate the search term without quotes (since the singleowner search ends with a quote)

2021-11-16 18:36 UTC, brtietz commented on ssc/cmod_cashloan.cpp
> +                                    //cf.at(CF_charging_cost_grid_month, a) += monthly_grid_to_batt[m] / (monthly_grid_to_batt[m] + monthly_grid_to_load[m]) * monthly_energy_charge[m] * charged_grid[
Do you mind removing the commented out lines prior to the merge?

2021-11-16 18:36 UTC, brtietz commented on ssc/cmod_equpartflip.cpp
> +                    //cf.at(CF_energy_net, i) = cf.at(CF_energy_sales, i) + cf.at(CF_energy_purchases, i); // Adding a positive and negative number
More commented out code - looks like the comment could also be removed?

2021-11-16 18:36 UTC, brtietz commented on ssc/cmod_equpartflip.cpp
> +                throw exec_error("singleowner", util::format("utility bill years (%d) not equal to analysis period years (%d).", (int)ub_count, nyears));
Issue with cmod name in exception

2021-11-16 18:36 UTC, brtietz commented on ssc/cmod_singleowner.cpp
> +            //+ cf.at(CF_energy_purchases_value, i);
Why is this commented out for singleowner but not the other compute modules?

2021-11-16 19:19 UTC, brtietz approved these changes
Great work! Thanks for doing the comment and exception cleanup. I think this is ready to go once the SAM side of things is ready to go.

2021-11-16 23:40 UTC, merged